//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cathedra
    {
        public cathedra()
        {
            this.teachers = new HashSet<teachers>();
        }
    
        public int cathedra_id { get; set; }
        public int faculty_id { get; set; }
        public string nameshort { get; set; }
        public string name { get; set; }
        public int cathedra_type_id { get; set; }
    
        public cathedra_type cathedra_type { get; set; }
        public ICollection<teachers> teachers { get; set; }
    }
}
