//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculty_type_all
    {
        public faculty_type_all()
        {
            this.faculty_all = new HashSet<faculty_all>();
        }
    
        public int faculty_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<faculty_all> faculty_all { get; set; }
    }
}
