//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VovksStudentEntities1 : DbContext
    {
        public VovksStudentEntities1()
            : base("name=VovksStudentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admpost_all> admpost_all { get; set; }
        public virtual DbSet<cathedra> cathedra { get; set; }
        public virtual DbSet<cathedra_type> cathedra_type { get; set; }
        public virtual DbSet<faculty_all> faculty_all { get; set; }
        public virtual DbSet<faculty_type_all> faculty_type_all { get; set; }
        public virtual DbSet<nagruzka_all> nagruzka_all { get; set; }
        public virtual DbSet<nagruzka_calc> nagruzka_calc { get; set; }
        public virtual DbSet<nagruzka_details> nagruzka_details { get; set; }
        public virtual DbSet<nagruzka_norm> nagruzka_norm { get; set; }
        public virtual DbSet<nagruzka_other> nagruzka_other { get; set; }
        public virtual DbSet<nagruzka_type> nagruzka_type { get; set; }
        public virtual DbSet<post_all> post_all { get; set; }
        public virtual DbSet<semester_all> semester_all { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
    }
}
