//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nagruzka_type
    {
        public nagruzka_type()
        {
            this.nagruzka_details = new HashSet<nagruzka_details>();
        }
    
        public int nagruzka_type_id { get; set; }
        public string name { get; set; }
        public Nullable<int> has_faculty { get; set; }
        public Nullable<int> has_kurs { get; set; }
        public Nullable<int> has_form { get; set; }
        public Nullable<int> has_specialty { get; set; }
        public Nullable<int> has_groups { get; set; }
        public Nullable<int> has_persons { get; set; }
        public Nullable<int> has_norm { get; set; }
        public Nullable<int> has_qty { get; set; }
        public int nagruzka_calc_id { get; set; }
        public Nullable<int> has_potok { get; set; }
        public Nullable<int> has_comment { get; set; }
        public string comment { get; set; }
        public Nullable<int> is_aud { get; set; }
    
        public virtual nagruzka_calc nagruzka_calc { get; set; }
        public virtual ICollection<nagruzka_details> nagruzka_details { get; set; }
    }
}
