//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nagruzka_all
    {
        public int nagruzka_id { get; set; }
        public int teacher_id { get; set; }
        public int zayavka_id { get; set; }
        public int faculty_id { get; set; }
        public string name { get; set; }
        public int kurs_id { get; set; }
        public int type_form_id { get; set; }
        public int specialization_id { get; set; }
        public int semester_id { get; set; }
        public int lec { get; set; }
        public int sem { get; set; }
        public int lab { get; set; }
        public int kons { get; set; }
        public int exam { get; set; }
        public int zal { get; set; }
        public int reyt { get; set; }
        public int kurs { get; set; }
        public int sam { get; set; }
        public string nazva1 { get; set; }
        public int hours1 { get; set; }
        public string nazva2 { get; set; }
        public int hours2 { get; set; }
        public string nazva3 { get; set; }
        public int hours3 { get; set; }
        public string nazva4 { get; set; }
        public int hours4 { get; set; }
        public string nazva5 { get; set; }
        public int hours5 { get; set; }
        public string potok { get; set; }
        public int tofaculty_id { get; set; }
        public int prac { get; set; }
        public int pot_kons { get; set; }
        public int mod_kontr { get; set; }
        public decimal credit { get; set; }
        public int students { get; set; }
        public int potok_gr { get; set; }
        public int subgroup { get; set; }
        public int plan_hours { get; set; }
        public int labgroup { get; set; }
        public int lec_inyaz { get; set; }
        public int exam_usno { get; set; }
        public int zal_usno { get; set; }
        public int roz_graph { get; set; }
        public int mod_calloc { get; set; }
        public int sam10 { get; set; }
        public int pragroup { get; set; }
        public int mod_kon_num { get; set; }
        public int roz_gra_num { get; set; }
        public int mod_cal_num { get; set; }
        public int acadgroup { get; set; }
        public int pidgroup { get; set; }
    
        public faculty_all faculty_all { get; set; }
        public semester_all semester_all { get; set; }
    }
}
