//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nagruzka_calc
    {
        public nagruzka_calc()
        {
            this.nagruzka_type = new HashSet<nagruzka_type>();
        }
    
        public int nagruzka_calc_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<nagruzka_type> nagruzka_type { get; set; }
    }
}
