//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nagruzka_other
    {
        public int nagruzka_other_id { get; set; }
        public int teacher_id { get; set; }
        public int year { get; set; }
        public int dek { get; set; }
        public int dip_b { get; set; }
        public int dip_s { get; set; }
        public int dip_m { get; set; }
        public int prym_kom { get; set; }
        public int prakt_dipl { get; set; }
        public int aspir { get; set; }
        public int prakt_vyr { get; set; }
        public int prakt_ped { get; set; }
        public int prakt_nav { get; set; }
        public int mpos { get; set; }
        public int kontr_vydv { get; set; }
        public int faculty_id { get; set; }
        public int org_pr { get; set; }
        public int spec_rada { get; set; }
        public int conference { get; set; }
        public int method_rada { get; set; }
        public int method_mon { get; set; }
        public int method_vak { get; set; }
        public int method_dak { get; set; }
        public int science_secr { get; set; }
        public int kurator { get; set; }
        public int dip_bz { get; set; }
        public int dip_sz { get; set; }
        public int dip_mz { get; set; }
    
        public virtual faculty_all faculty_all { get; set; }
        public virtual teachers teachers { get; set; }
    }
}
