//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Provider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nagruzka_norm
    {
        public nagruzka_norm()
        {
            this.nagruzka_details = new HashSet<nagruzka_details>();
        }
    
        public int nagruzka_norm_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<nagruzka_details> nagruzka_details { get; set; }
    }
}
